config/routes.rb
Rails.application.routes.draw do
	
	root 'songs#index'
	get '/songs/:id/docs', to: 'songs#docs'
	get '/songs/:id/collections', to: 'songs#collections'

	get '/books', to: 'docs#books'

	resources :categories
	resources :songs
	resources :song_collections
	resources :collections
	resources :docs
	resources :resources
	
	get '/resources/:id/destroy', to: 'resources#destroy'
	get '/resources/destroy_confirmation', to: 'resources#destroy_confirmation'
end

app/views/resources/_cloud_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
			<li class="nav-item">
        <a class="nav-link" href="<%= cloudinary_index_path %>">CLOUDresources</a>
      </li>
			<li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">DBresources</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pdfs_path %>">Pdfs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= images_path %>">Images</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_path %>">New</a>
      </li>
    </ul>
  </div>
</nav>

app/views/resources/_image_box.html.erb
<div>
  <div class="public_id">
    <%= upload["public_id"] %>
		<%= image_tag(upload["url"]) %>
		<%= link_to 'Delete image', resource_path(upload["public_id"]) + '/destroy', resource: upload,  method: 'DELETE' %>
	</div>
</div>

app/views/resources/destroy_confirmation.html.erb
<h2>You have successfully deleted a resource.</h2>

app/views/resources/images.html.erb
<div class='row'>
	<div class='col-lg-12'>
	<ul>
	<% @images.each do |image| %>
		<%= render partial: 'image_box', locals: {upload: image} %>
		<hr />
		<% end %>
	</ul>
		</div>
</div>
 

app/views/resources/index.html.erb
<% @resources.each do |res| %>
	<ul>
	<li>public_id: <%= res["public_id"] %></li>
	<li>format: <%= res["format"] %></li>
	<li>created_at: <%= res["created_at"] %></li>
	<li>width: <%= res["width"] %></li>
	<li>height: <%= res["height"] %></li>
	<li>url: <%= link_to 'show_image', res["url"] %></li>
	<li>secure_url: <%= res["secure_url"] %></li>
	<li><%= link_to 'Delete resource', resources_path(res['public_id']), {resource: res,  method: 'DELETE'}%>
 
	</li>
	<hr />
	</ul>
	<% end %>
<hr />
 

app/views/resources/index_cloudinary.html.erb
<h1>
  Uploads and Transformations
</h1>

<% @resources.each do |resource| %>
 
	Name: <%= resource["url"].split('/').last.gsub('%20', '') %>
	URL: <%= resource.secure_url %>
	 
<% end %>

app/views/resources/new.html.erb
<%= form_for @resource do |f| %>
	<%= f.label :file %>	
	<%= f.file_field :file %>	
	
	<%= f.submit %>
<% end %>

app/views/resources/pdfs.html.erb
<div class='row'>
	<div class='col-lg-12'>
	<% @pdfs.each do |pdf| %>
		<ul>
			<strong><li><%= link_to pdf["secure_url"].split('/').last.gsub('.pdf', '').gsub('%20', ' '), pdf["url"] %></li></strong>
			<li>format: <%= pdf["format"] %></li>
			<li>secure_url: <%= pdf["secure_url"] %></li>
		</ul>
		<hr />
		<% end %>
	</div>
</div>
 

app/views/resources/resource_not_created.html.erb
<h2>Resource NOT created.</h2>

app/views/resources/show.html.erb
	<%= @resource.public_id %>
	<%= @resource.url %>
	<%= @resource.secure_url %>
	<%= @resource.width %>
	<%= @resource.height %>
	<%= @resource.format %>